### PR TITLE
CSS changes

### PR DESCRIPTION
**Pull request by E-fais**
Extra button removed.
Added space between input field and button.
Removed extra white space that overflows at right side by adjusting image size.

-------------------------------------------------------------------------------------------------------------------------------------
Shopify - Google Chrome 21-02-2023 7 36 44 PM

### CODE REVIEW

**Comment by E-fais** [comment]
It resolve #1

**Comment by Saadat-B** [comment]
Hey Fais I'm not able to reproduce this issue. 
Can you share how to reproduce it. 

> Extra button removed.

Also we don't need to remove the button. 

Just the space would be fine I think.

Can you provide the width of your display screen?

Here's the screenshot of the website which i'm able to see right now - 

Screenshot from 2023-02-21 23-02-44

**Comment by E-fais** [comment]
The website is looking good in your screen shot, I dont know exactly how to fix this issue. Let me close this PR now.

**Comment by Saadat-B** [comment]
Thank you Fais for taking your time out to contribute to the project and thank you for closing the issue 😄 
I hope we can collaborate in the future!👍🏻

**Comment by E-fais** [comment]
> Thank you Fais for taking your time out to contribute to the project and thank you for closing the issue 😄 I hope we can collaborate in the future!👍🏻

Ofcourse yes brother, let's learn together 👍

**Pull request closed without merging**
